# cluster and index info here
general:
 es_host: "10.86.64.31"
 index: "test_data"


# conf for read module
read_module:
 # specify the rate to achived. How many threads to work and how many hits for each of them
 number_of_threads: 200
 hits_per_thread: 20
 # set a division number to report process while the benchmark is being executed
 division_report: 10
 # set it to specify how much msecs to wait for an es response
 timeout: 1000.00

# conf for write module
write_module:
 # specify the rate to achived. How many threads to work and how many hits for each of them
 number_of_threads: 10000
 #hits_per_thread must > batch_size
 hits_per_thread: 30
 # set a division number to report process while the benchmark is being exected
 division_report: 10
 # set a batch size. Useful for write module
 batch_size: 10
 # set it to specify how much msecs to wait for an es response
 timeout: 1000.00
